#!/bin/sh
# Bundle every card into dist/jackery-lovelace-cards.js, the single file HACS installs.
set -eu
cd "$(dirname "$0")/.."

VERSION=$(cat VERSION)
OUT=dist/jackery-lovelace-cards.js
CARDS="jackery-ts-plan-card.js jackery-circuit-panel.js jackery-schedule-heatmap.js jackery-power-status-card.js jackery-battery-pack-card.js jackery-portable-card.js"

mkdir -p dist
{
  echo "// Generated by scripts/build.sh from the jackery-*.js sources. Do not edit."
  echo "console.info(\"%c jackery-lovelace-cards %c $VERSION \", \"background:#f39c12;color:#fff\", \"background:#ddd;color:#000\");"
  for card in $CARDS; do
    # Block-scope each card so top-level const/class names can't collide.
    printf '\n// ---- %s ----\n{\n' "$card"
    cat "$card"
    printf '}\n'
  done
} > "$OUT"
echo "Built $OUT ($VERSION)"
